Propuesta de visualización de cupos mediante D3
open-source-uc/ramos-uc pull request #103
Opened 2022-12-23 21:19 UTC by EnzoMorata

Se implementa una propuesta de visualización para los cupos de los ramos utilizando D3.js, fue instalado de forma manual (npm install d3). La herramienta de visualización hecha busca mantener la mayoría de funcionalidades y continuar con el diseño actualmente en uso.

Para indicar a qué banner corresponde cada dato se incluyó la información dentro del tooltip al pasar el mouse por encima de cada punto #4 .

Para modificar el rango de fechas en que son visualizados los datos, se optó por implementar zoom dentro de la visualización y que se modifiquen únicamente los datos en el eje horizontal. Permitiendo modificar el periodo en que son visualizados los datos de forma dinámica por el usuario y sin necesidad de un input #35 . 

Es posible que sea necesario ajustar ciertos valores y realizar correcciones, ya que al levantar el servidor de forma local los datos de prueba que utilicé no son representativos. Además, de haberlo probado únicamente desde mi computador. También, hay varios elementos provenientes de la implementación de la visualización con Google Charts que siguen presentes y que preferí no modificar.

Agradecería cualquier tipo de retroalimentación para ir mejorando la visualización.

2022-12-23 22:57 UTC, nico-mac commented
Muy buena propuesta! Sin duda faltan algunos detalles por afinar pero va bien encaminada.

![image](https://user-images.githubusercontent.com/16323007/209411605-1da500be-7bff-4c60-974e-be37836c330c.png)

## Aspectos a notar
+ Hay un circulo que queda cargando infinitamente.
+ El zoom funciona muy bien, me gusta, aunque también funciona cuando se hace desde el espacio lateral al gráfico, lo que hace un comportamiento inesperado
+ Los tooltips funcionan bastante mejor que la implementación original, solo les eliminaria el *tag* de "Banner:" porque esa información está mala en la base de datos de producción.

Lo otro, si quieres me mandas un mail y te puedo enviar un backup de la base de datos (nicomcintyrew@gmail.com)

2022-12-23 23:03 UTC, nico-mac requested changes
El código principal parece bien y funciona. Trata de cambiar lo que dejé en el comentario. Para que quede limpio e instalable por todos debieras agregar d3 al package.json y eliminar todos los rastros de Google Charts.

2022-12-23 23:03 UTC, nico-mac commented on front/assets/src/utils/quota.js
> -    ga_event("detail", { event_category: "follow", event_label: response.initials })
Esa línea debiera quedar, es para hacer analytics.

2023-01-01 19:11 UTC, EnzoMorata commented
Terminé de aplicar los cambios propuestos anteriormente. También, agregué un par de cambios para mejorar algunos aspectos en la interacción y resolví unos errores de funcionamiento que noté al probar la visualización con datos reales.

2023-01-04 23:05 UTC, nico-mac approved these changes

2023-01-04 23:05 UTC, nico-mac commented
Gracias @EnzoMorata voy a hacer el merge.

2023-01-04 23:06 UTC, merged