Add devcontainer support
open-source-uc/ramos-uc pull request #13
Opened 2021-07-16 04:16 UTC by agucova

Resolviendo #12, al menos por el lado del desarrollador, esto agrega un entorno replicable que utiliza [development containers](https://code.visualstudio.com/docs/remote/containers) de Visual Studio Code para crear un entorno de desarollo replicable de Docker en segundos.

Esto gestiona las dependencias, base de datos, pre-commit y migraciones. Lo único que hay que hacer manualmente es agregar las credenciales OAuth.

Como bonus, añadí un .gitattributes para prevenir errores de line endings por la diferencia de entornos (y aproveché de añadirle reglas específicas para Python), y  agregué un script de launch para VSCode.

2021-07-16 18:43 UTC, nico-mac commented
¿Es necesario tener VSCode para poder usar este contenedor, cierto? No me gusta la idea de "casarnos" con un IDE, en lo personal yo uso VSCode como un editor de texto inteligente y no me gustaría tener alta dependencia con este ni con ningún otro IDE.

Sabiendo que si puede ser útil, podríamos dejar esto en una branch `develop` hasta armar un Docker container independiente y con lo necesario para llevarlo a producción.
¿Que opinan?

2021-07-16 20:52 UTC, agucova commented
Estoy de acuerdo, y de todas formas vamos a necesitar el contenedor general, pero la ventaja de un devcontainer es que se integra directamente con las herramientas de debug y sistema de archivos de VSCode.

Creo que no son cosas mutuamente excluyentes, y se puede armar uno a partir del otro.

2021-07-16 21:03 UTC, agucova commented
Efectivamente:
> Can I just reuse an existing container image or Docker / Docker Compose configuration?

> Yes! If you have a Dockerfile or Docker Compose file in your project/repository, follow the same steps to add a definition and you'll be prompted to select a Dockerfile or Docker Compose file and customize from there. If you then commit these files to a Git repository, you can use it with GitHub Codespaces as well. If you prefer, you can also start up the container manually and attach to it. However, note that many images will be missing things like git that you will want to use. There are scripts in the script-library like the common script that can help adding these to your existing Dockerfile or image.

2021-07-17 01:52 UTC, FarDust requested changes

2021-07-17 01:52 UTC, FarDust commented on .env.example
> -LANGUAGE = es-cl
Eliminar el `SECRET_KEY` del archivo de ejemplo, es quitar documentación. Lo cual debería quedar en el README o mantenerse en este archivo.

2021-07-17 02:55 UTC, agucova commented on .env.example
> -LANGUAGE = es-cl
No entendí el punto, por qué sería mejor quitarlo? Entiendo que en producción es importante definir un SECRET_KEY y el workflow hace improbable que alguien lo commitee sin querer (y de todas formas sabríamos inmediatamente gracias a GitHub).

2021-07-17 02:55 UTC, agucova commented on .env.example
> -LANGUAGE = es-cl
Igual en desarollo lo dejo vacío, ni idea que hace Django cuando es así jajajaja

2021-07-17 02:56 UTC, agucova commented on .env.example
> -LANGUAGE = es-cl
Oops, eso fue totalmente accidental. Buen ojo.

2021-07-17 03:10 UTC, FarDust approved these changes

2021-07-17 03:12 UTC, agucova commented
@nico-mac estarías de acuerdo con mergear y hacer un follow-up para agregar una imagen mas general?

2021-07-17 03:56 UTC, nico-mac commented
Hagamos el merge, pero queda pendiente hacer el contenedor general y depués "descasarnos" de VSCode.

2021-07-17 03:57 UTC, nico-mac approved these changes

2021-07-17 04:06 UTC, nico-mac requested changes

2021-07-17 04:06 UTC, nico-mac commented on docs/SETUP.md
> +1## Using devcontainer
Un detalle, ahí se te pasó un "1".

2021-07-17 05:43 UTC, agucova commented on docs/SETUP.md
> +1## Using devcontainer
Resuelto

2021-07-17 05:43 UTC, merged