Scrapping: Refactorización y agendamiento
open-source-uc/ramos-uc pull request #23
Opened 2021-07-20 04:53 UTC by nico-mac

+ Se refactorizó el módulo de scrapping para convertirlo en Django app.
+ El script de banner se integró con el resto del scraper.
+ Se incorporó la configuración del scrapping dentro de las configuraciones de Django (antes estaba en un archivo independiente `settings.json`.
+ Se eliminó el script `json_dump.py`, el cual no tenía ningún uso.
+ Se instaló [django-background-tasks](https://django-background-tasks.readthedocs.io/) para agendar el scrapping y se creó una view para realizar el agendamiento.
+ Se permitió la configuración de la zona horaria desde el *enviroment* (Necesario para poder agendar correctamente)

2021-07-20 05:04 UTC, agucova commented
Estoy en peak de exámenes así que puedo revisarlo después del miércoles. Espero que Gabriel pueda :eyes:

2021-07-20 19:27 UTC, nico-mac commented
Buena idea, voy a agregarlos cuando tenga tiempo.

2021-07-22 06:50 UTC, agucova requested changes

2021-07-22 06:50 UTC, agucova commented on ramosuc/settings.py
> +TIME_ZONE = os.getenv("TIME_ZONE", "UTC")
Pregunta, ¿Por qué aquí el defecto es UTC y no America/Santiago como el resto?

2021-07-22 06:50 UTC, agucova commented on .env.example
Se podría agregar `SCRAPE_LOG`, supongo.

2021-07-22 06:50 UTC, agucova commented on docs/SCHEDULER.md
> +It is recomended to daemonize or supervise this process on production enviroments.
Podría ser útil comunicar cual es el intervalo recomendado.

2021-07-22 06:50 UTC, agucova commented on docs/SCRAPER.md
> +Also, scrapping can be scheduled from `/scraper` url (only allowed for staff users). See [scheduler docs](SCHEDULER.md) for more details on how scheduling works.
Bordeando la pedancia, pero es "scraping" con una p.

2021-07-22 06:50 UTC, agucova commented on .env.example
Ok, me di cuenta que no es configurable por el entorno. Me parece razonable, aunque tal vez podría configurarse `BASE_DIR`.

2021-07-22 06:50 UTC, agucova commented on apps/bc_scraper/actions/banner.py
> +    except Exception as err:
Esto es un antipatrón que resulta en perder el traceback y no seguir la convención de usar códigos de retorno distintos de cero cuando algo sale mal. Cualquier programa supervisor asumiría que fue una ejecución exitosa. 

Por lo demás `exit()` está diseñado para sesiones interactivas y no funciona en algunos contextos de ejecución (como cuando el módulo `site` no está presente). Esto tiene el riesgo de mantener ejecución tras el error.

Eliminaría el `except` completamente o bien agregaría logging y usaría `sys.exit(1)`.

2021-07-22 06:50 UTC, agucova commented on apps/bc_scraper/actions/banner.py
> +    except Exception as err:
Sobre esto, parece que este mismo patrón está en varias partes del código:
```shell
➜ grep -rn --exclude-dir='.?*' "exit()" .
./scrape/actions/delete.py:21:        exit()
./scrape/actions/collect.py:26:        exit()
./scrape/actions/update.py:25:        exit()
./scrape/main.py:43:    exit()
./scrape/main.py:50:    exit()
./scrape/main.py:64:        exit()
./scrape/old_banner.py:14:    exit()
```

2021-07-22 06:50 UTC, agucova commented on ramosuc/settings.py
> +TIME_ZONE = os.getenv("TIME_ZONE", "UTC")
Lo digo porque me preocupa que un usuario pueda fácilmente instalar el software con timezones inconsistentes.

2021-07-22 20:54 UTC, nico-mac commented on ramosuc/settings.py
> +TIME_ZONE = os.getenv("TIME_ZONE", "UTC")
Este es el único default como tal. El resto son solo ejemplos. Dejando UTC como default permite no romper nada anterior.

2021-07-22 20:58 UTC, nico-mac commented on docs/SCHEDULER.md
> +It is recomended to daemonize or supervise this process on production enviroments.
Lo recomendable sería que este corriendo 24/7. Vi que la documentación oficial sugiere usar un cron job por simplicidad, pero yo recomendaría usar supervisor o algo similar (sin intervalos).

No se si te referías a eso?

2021-07-22 21:02 UTC, nico-mac commented
Hice algunos tests y eliminé el anti-patrón, feliz si lo pueden revisar

2021-07-22 21:50 UTC, agucova commented
Arreglé otro pequeño typo que noté. Puedes actualizar los requirements.txt corriendo:
```shell
poetry export > requirements.txt
poetry export --dev > requirements-dev.txt
```

2021-07-22 21:52 UTC, agucova approved these changes
Todo listo.

2021-07-22 21:58 UTC, merged