buscacursos button
open-source-uc/ramos-uc pull request #25
Opened 2021-07-23 00:08 UTC by mc-cari

2021-07-23 00:20 UTC, nico-mac commented on front/assets/webpack.config.js
> +    course_link: './src/course_link.js',
Esto no es necesario, solo se usa para crear archivos compilados independientes, en este caso esta incluido dentro del `planner.js`.

2021-07-23 00:24 UTC, nico-mac requested changes
No creo que valga la pena hacer la función `link` en un archivo separado, mejor incluir ese código directamente dentro de buscacursos. Lo otro, usar nombre de variables un poco mas autoexplicativos y ojalá borrar el console.log.

Se ve muy bien!

2021-07-23 03:26 UTC, mc-cari commented
Tengo dos dudas:

- Hay que agregar el respectivo Google Analytics?
- Hay que crear otra pull request?

2021-07-23 04:02 UTC, agucova commented
@mc-cari No es necesario hacer otro PR, ya que si haces nuevos commits aparecen aquí automáticamente. Con respecto a Google Analytics, no veo ninguna necesidad de agregar un evento al botón.

2021-07-24 14:41 UTC, nico-mac approved these changes

2021-07-24 14:42 UTC, merged